# Generated by Django 4.1.3 on 2022-12-19 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartfridge', '0002_listofproduct_in_fridge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
