# Generated by Django 4.1.3 on 2023-01-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfridge', '0004_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
