# Generated by Django 4.1.3 on 2023-01-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartfridge', '0005_alter_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='id_user',
        ),
    ]
