# Generated by Django 4.1.3 on 2023-01-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
